"""
Seed data: 12 business entity profiles across hospitality, real estate, and wellness.
"""

SEED_ENTITIES = [
    {
        "id": "entity_01",
        "name": "Coastal Grand Hotel",
        "canonical_name": "coastal grand hotel",
        "vertical": "hospitality",
        "address_patterns": ["247 Harbour Rd", "Coastal Business Park", "CGH"],
        "known_vendor_categories": [
            "Food Service", "Commercial Linen", "HVAC", "Cleaning",
            "Security", "Landscaping", "Pest Control", "Laundry",
        ],
        "po_number_format": r"CGH-\d{4}-\d{4}",
        "typical_amount_min": 500,
        "typical_amount_max": 50000,
        "routing_email": "ap@coastalgrandhotel.com",
        "review_contact": "finance@coastalgrandhotel.com",
    },
    {
        "id": "entity_02",
        "name": "Harbour Suites & Conference Centre",
        "canonical_name": "harbour suites conference centre",
        "vertical": "hospitality",
        "address_patterns": ["88 Marina Blvd", "Harbour Business District", "HSCC"],
        "known_vendor_categories": [
            "Food Service", "Commercial Linen", "AV Equipment", "Cleaning",
            "Floral", "Catering", "Event Supplies",
        ],
        "po_number_format": r"HSC-\d{4}-\d{4}",
        "typical_amount_min": 300,
        "typical_amount_max": 30000,
        "routing_email": "ap@harboursuites.com",
        "review_contact": "finance@harboursuites.com",
    },
    {
        "id": "entity_03",
        "name": "The Summit Resort & Spa",
        "canonical_name": "summit resort spa",
        "vertical": "hospitality",
        "address_patterns": ["1 Summit Drive", "Mountain Resort District", "TSR"],
        "known_vendor_categories": [
            "Food Service", "Spa Supplies", "Commercial Linen", "Landscaping",
            "HVAC", "Pool Maintenance", "Fitness Equipment",
        ],
        "po_number_format": r"TSR-\d{4}-\d{4}",
        "typical_amount_min": 1000,
        "typical_amount_max": 75000,
        "routing_email": "ap@summitresort.com",
        "review_contact": "finance@summitresort.com",
    },
    {
        "id": "entity_04",
        "name": "Pacific Inn Group Operations",
        "canonical_name": "pacific inn group",
        "vertical": "hospitality",
        "address_patterns": ["Pacific Business Centre", "555 Pacific Blvd", "PIG"],
        "known_vendor_categories": [
            "Food Service", "Cleaning", "Maintenance", "Security",
            "IT Services", "Uniforms", "Vending",
        ],
        "po_number_format": r"PIG-\d{4}-\d{4}",
        "typical_amount_min": 200,
        "typical_amount_max": 25000,
        "routing_email": "ap@pacificinn.com",
        "review_contact": "finance@pacificinn.com",
    },
    {
        "id": "entity_05",
        "name": "Bayside Hotel & Events",
        "canonical_name": "bayside hotel events",
        "vertical": "hospitality",
        "address_patterns": ["Bayside Marina", "99 Waterfront Ave", "BHE"],
        "known_vendor_categories": [
            "Food Service", "Event Equipment", "Floral", "Linen",
            "Cleaning", "Photography", "Entertainment",
        ],
        "po_number_format": r"BHE-\d{4}-\d{4}",
        "typical_amount_min": 500,
        "typical_amount_max": 40000,
        "routing_email": "ap@baysidehotel.com",
        "review_contact": "finance@baysidehotel.com",
    },
    {
        "id": "entity_06",
        "name": "Pacific Commercial Properties Ltd",
        "canonical_name": "pacific commercial properties",
        "vertical": "real_estate",
        "address_patterns": ["Pacific Tower", "1000 Commerce St", "PCP"],
        "known_vendor_categories": [
            "Property Maintenance", "Cleaning", "Security", "HVAC",
            "Electrical", "Plumbing", "Janitorial", "Parking Management",
        ],
        "po_number_format": r"PCP-\d{4}-\d{4}",
        "typical_amount_min": 1000,
        "typical_amount_max": 100000,
        "routing_email": "ap@pacificcommercial.com",
        "review_contact": "finance@pacificcommercial.com",
    },
    {
        "id": "entity_07",
        "name": "Harbour View Residential",
        "canonical_name": "harbour view residential",
        "vertical": "real_estate",
        "address_patterns": ["Harbour View Tower", "200 Harbour Drive", "HVR"],
        "known_vendor_categories": [
            "Property Maintenance", "Landscaping", "Cleaning", "HVAC",
            "Elevator Services", "Window Cleaning", "Concierge Services",
        ],
        "po_number_format": r"HVR-\d{4}-\d{4}",
        "typical_amount_min": 500,
        "typical_amount_max": 60000,
        "routing_email": "ap@harbourview.com",
        "review_contact": "finance@harbourview.com",
    },
    {
        "id": "entity_08",
        "name": "Summit Land Holdings",
        "canonical_name": "summit land holdings",
        "vertical": "real_estate",
        "address_patterns": ["Summit Corporate Park", "500 Highland Ave", "SLH"],
        "known_vendor_categories": [
            "Land Development", "Legal Services", "Survey", "Environmental",
            "Construction", "Architecture", "Engineering", "Permits",
        ],
        "po_number_format": r"SLH-\d{4}-\d{4}",
        "typical_amount_min": 5000,
        "typical_amount_max": 500000,
        "routing_email": "ap@summitland.com",
        "review_contact": "finance@summitland.com",
    },
    {
        "id": "entity_09",
        "name": "Metro Property Management",
        "canonical_name": "metro property management",
        "vertical": "real_estate",
        "address_patterns": ["Metro Business Centre", "333 Metro Blvd", "MPM"],
        "known_vendor_categories": [
            "Property Maintenance", "Cleaning", "Security", "IT Services",
            "Insurance", "Accounting", "Legal", "Tenant Services",
        ],
        "po_number_format": r"MPM-\d{4}-\d{4}",
        "typical_amount_min": 300,
        "typical_amount_max": 45000,
        "routing_email": "ap@metroproperty.com",
        "review_contact": "finance@metroproperty.com",
    },
    {
        "id": "entity_10",
        "name": "Serenity Wellness Studios",
        "canonical_name": "serenity wellness studios",
        "vertical": "wellness",
        "address_patterns": ["Wellness District", "77 Serenity Lane", "SWS"],
        "known_vendor_categories": [
            "Spa Supplies", "Essential Oils", "Fitness Equipment", "Towels & Linens",
            "Cleaning", "Supplements", "Candles", "Aromatherapy",
        ],
        "po_number_format": r"SWS-\d{4}-\d{4}",
        "typical_amount_min": 200,
        "typical_amount_max": 15000,
        "routing_email": "ap@serenitywellness.com",
        "review_contact": "finance@serenitywellness.com",
    },
    {
        "id": "entity_11",
        "name": "Pure Life E-Commerce",
        "canonical_name": "pure life ecommerce",
        "vertical": "wellness",
        "address_patterns": ["Pure Life Warehouse", "888 Commerce Way", "PLE"],
        "known_vendor_categories": [
            "Health Supplements", "Organic Products", "Packaging", "Shipping Supplies",
            "Digital Marketing", "Web Services", "Photography",
        ],
        "po_number_format": r"PLE-\d{4}-\d{4}",
        "typical_amount_min": 1000,
        "typical_amount_max": 80000,
        "routing_email": "ap@purelife.com",
        "review_contact": "finance@purelife.com",
    },
    {
        "id": "entity_12",
        "name": "Vitality Health Retail",
        "canonical_name": "vitality health retail",
        "vertical": "wellness",
        "address_patterns": ["Vitality Plaza", "444 Health Blvd", "VHR"],
        "known_vendor_categories": [
            "Health Products", "Supplements", "Retail Fixtures", "Packaging",
            "IT Services", "POS Systems", "Display Materials",
        ],
        "po_number_format": r"VHR-\d{4}-\d{4}",
        "typical_amount_min": 500,
        "typical_amount_max": 50000,
        "routing_email": "ap@vitalityhealth.com",
        "review_contact": "finance@vitalityhealth.com",
    },
]
