"""
Seed data: 50 business entity profiles across 8 verticals.
"""

SEED_ENTITIES = [
    # ── Hospitality (10) ──────────────────────────────────────────────────────
    {
        "id": "entity_01",
        "name": "Coastal Grand Hotel",
        "canonical_name": "coastal grand hotel",
        "vertical": "hospitality",
        "address_patterns": ["247 Harbour Rd", "Coastal Business Park", "CGH"],
        "known_vendor_categories": [
            "Food Service", "Commercial Linen", "HVAC", "Cleaning",
            "Security", "Landscaping", "Pest Control", "Laundry",
        ],
        "po_number_format": r"CGH-\d{4}-\d{4}",
        "typical_amount_min": 500,
        "typical_amount_max": 50000,
        "routing_email": "ap@coastalgrandhotel.com",
        "review_contact": "finance@coastalgrandhotel.com",
    },
    {
        "id": "entity_02",
        "name": "Harbour Suites & Conference Centre",
        "canonical_name": "harbour suites conference centre",
        "vertical": "hospitality",
        "address_patterns": ["88 Marina Blvd", "Harbour Business District", "HSCC"],
        "known_vendor_categories": [
            "Food Service", "Commercial Linen", "AV Equipment", "Cleaning",
            "Floral", "Catering", "Event Supplies",
        ],
        "po_number_format": r"HSC-\d{4}-\d{4}",
        "typical_amount_min": 300,
        "typical_amount_max": 30000,
        "routing_email": "ap@harboursuites.com",
        "review_contact": "finance@harboursuites.com",
    },
    {
        "id": "entity_03",
        "name": "The Summit Resort & Spa",
        "canonical_name": "summit resort spa",
        "vertical": "hospitality",
        "address_patterns": ["1 Summit Drive", "Mountain Resort District", "TSR"],
        "known_vendor_categories": [
            "Food Service", "Spa Supplies", "Commercial Linen", "Landscaping",
            "HVAC", "Pool Maintenance", "Fitness Equipment",
        ],
        "po_number_format": r"TSR-\d{4}-\d{4}",
        "typical_amount_min": 1000,
        "typical_amount_max": 75000,
        "routing_email": "ap@summitresort.com",
        "review_contact": "finance@summitresort.com",
    },
    {
        "id": "entity_04",
        "name": "Pacific Inn Group Operations",
        "canonical_name": "pacific inn group",
        "vertical": "hospitality",
        "address_patterns": ["Pacific Business Centre", "555 Pacific Blvd", "PIG"],
        "known_vendor_categories": [
            "Food Service", "Cleaning", "Maintenance", "Security",
            "IT Services", "Uniforms", "Vending",
        ],
        "po_number_format": r"PIG-\d{4}-\d{4}",
        "typical_amount_min": 200,
        "typical_amount_max": 25000,
        "routing_email": "ap@pacificinn.com",
        "review_contact": "finance@pacificinn.com",
    },
    {
        "id": "entity_05",
        "name": "Bayside Hotel & Events",
        "canonical_name": "bayside hotel events",
        "vertical": "hospitality",
        "address_patterns": ["Bayside Marina", "99 Waterfront Ave", "BHE"],
        "known_vendor_categories": [
            "Food Service", "Event Equipment", "Floral", "Linen",
            "Cleaning", "Photography", "Entertainment",
        ],
        "po_number_format": r"BHE-\d{4}-\d{4}",
        "typical_amount_min": 500,
        "typical_amount_max": 40000,
        "routing_email": "ap@baysidehotel.com",
        "review_contact": "finance@baysidehotel.com",
    },
    {
        "id": "entity_06_h",
        "name": "Riverside Inn & Suites",
        "canonical_name": "riverside inn suites",
        "vertical": "hospitality",
        "address_patterns": ["12 Riverside Crescent", "Riverside District", "RIS"],
        "known_vendor_categories": [
            "Food Service", "Commercial Linen", "Cleaning", "Plumbing",
            "Electrical", "Parking", "Wi-Fi Infrastructure",
        ],
        "po_number_format": r"RIS-\d{4}-\d{4}",
        "typical_amount_min": 400,
        "typical_amount_max": 35000,
        "routing_email": "ap@riversideinn.com",
        "review_contact": "finance@riversideinn.com",
    },
    {
        "id": "entity_07_h",
        "name": "Mountain Peak Lodge",
        "canonical_name": "mountain peak lodge",
        "vertical": "hospitality",
        "address_patterns": ["Peak Road Alpine Village", "MPL", "Mountain Escape"],
        "known_vendor_categories": [
            "Food Service", "Ski Equipment", "Outdoor Gear", "Linen",
            "Maintenance", "Transportation", "Snowplowing",
        ],
        "po_number_format": r"MPL-\d{4}-\d{4}",
        "typical_amount_min": 800,
        "typical_amount_max": 60000,
        "routing_email": "ap@mountainpeaklodge.com",
        "review_contact": "finance@mountainpeaklodge.com",
    },
    {
        "id": "entity_08_h",
        "name": "The Urban Grand Hotel",
        "canonical_name": "urban grand hotel",
        "vertical": "hospitality",
        "address_patterns": ["1 Central Plaza", "Downtown Hotel District", "UGH"],
        "known_vendor_categories": [
            "Food Service", "Concierge Supplies", "Valet", "Linen",
            "Cleaning", "Security", "Business Centre",
        ],
        "po_number_format": r"UGH-\d{4}-\d{4}",
        "typical_amount_min": 1000,
        "typical_amount_max": 80000,
        "routing_email": "ap@urbangrandhotel.com",
        "review_contact": "finance@urbangrandhotel.com",
    },
    {
        "id": "entity_09_h",
        "name": "Garden Terrace Hotel",
        "canonical_name": "garden terrace hotel",
        "vertical": "hospitality",
        "address_patterns": ["300 Garden Ave", "Suburban Hotel Zone", "GTH"],
        "known_vendor_categories": [
            "Food Service", "Landscaping", "Gardening", "Linen",
            "Pool Maintenance", "Cleaning", "Pest Control",
        ],
        "po_number_format": r"GTH-\d{4}-\d{4}",
        "typical_amount_min": 300,
        "typical_amount_max": 28000,
        "routing_email": "ap@gardenterracehotel.com",
        "review_contact": "finance@gardenterracehotel.com",
    },
    {
        "id": "entity_10_h",
        "name": "The Peninsula Club",
        "canonical_name": "peninsula club",
        "vertical": "hospitality",
        "address_patterns": ["Peninsula Waterfront", "Elite Members District", "TPC"],
        "known_vendor_categories": [
            "Fine Dining", "Luxury Linen", "Concierge", "Marina Services",
            "Yacht Maintenance", "Premium Spirits", "Private Events",
        ],
        "po_number_format": r"TPC-\d{4}-\d{4}",
        "typical_amount_min": 2000,
        "typical_amount_max": 120000,
        "routing_email": "ap@peninsulaclub.com",
        "review_contact": "finance@peninsulaclub.com",
    },

    # ── Real Estate (10) ──────────────────────────────────────────────────────
    {
        "id": "entity_11_re",
        "name": "Pacific Commercial Properties Ltd",
        "canonical_name": "pacific commercial properties",
        "vertical": "real_estate",
        "address_patterns": ["Pacific Tower", "1000 Commerce St", "PCP"],
        "known_vendor_categories": [
            "Property Maintenance", "Cleaning", "Security", "HVAC",
            "Electrical", "Plumbing", "Janitorial", "Parking Management",
        ],
        "po_number_format": r"PCP-\d{4}-\d{4}",
        "typical_amount_min": 1000,
        "typical_amount_max": 100000,
        "routing_email": "ap@pacificcommercial.com",
        "review_contact": "finance@pacificcommercial.com",
    },
    {
        "id": "entity_12_re",
        "name": "Harbour View Residential",
        "canonical_name": "harbour view residential",
        "vertical": "real_estate",
        "address_patterns": ["Harbour View Tower", "200 Harbour Drive", "HVR"],
        "known_vendor_categories": [
            "Property Maintenance", "Landscaping", "Cleaning", "HVAC",
            "Elevator Services", "Window Cleaning", "Concierge Services",
        ],
        "po_number_format": r"HVR-\d{4}-\d{4}",
        "typical_amount_min": 500,
        "typical_amount_max": 60000,
        "routing_email": "ap@harbourview.com",
        "review_contact": "finance@harbourview.com",
    },
    {
        "id": "entity_13_re",
        "name": "Summit Land Holdings",
        "canonical_name": "summit land holdings",
        "vertical": "real_estate",
        "address_patterns": ["Summit Corporate Park", "500 Highland Ave", "SLH"],
        "known_vendor_categories": [
            "Land Development", "Legal Services", "Survey", "Environmental",
            "Construction", "Architecture", "Engineering", "Permits",
        ],
        "po_number_format": r"SLH-\d{4}-\d{4}",
        "typical_amount_min": 5000,
        "typical_amount_max": 500000,
        "routing_email": "ap@summitland.com",
        "review_contact": "finance@summitland.com",
    },
    {
        "id": "entity_14_re",
        "name": "Metro Property Management",
        "canonical_name": "metro property management",
        "vertical": "real_estate",
        "address_patterns": ["Metro Business Centre", "333 Metro Blvd", "MPM"],
        "known_vendor_categories": [
            "Property Maintenance", "Cleaning", "Security", "IT Services",
            "Insurance", "Accounting", "Legal", "Tenant Services",
        ],
        "po_number_format": r"MPM-\d{4}-\d{4}",
        "typical_amount_min": 300,
        "typical_amount_max": 45000,
        "routing_email": "ap@metroproperty.com",
        "review_contact": "finance@metroproperty.com",
    },
    {
        "id": "entity_15_re",
        "name": "Coastal Development Group",
        "canonical_name": "coastal development group",
        "vertical": "real_estate",
        "address_patterns": ["Coastal Heights", "75 Cliffside Way", "CDG"],
        "known_vendor_categories": [
            "Construction", "Architecture", "Civil Engineering", "Permits",
            "Environmental Impact", "Survey", "Geotechnical",
        ],
        "po_number_format": r"CDG-\d{4}-\d{4}",
        "typical_amount_min": 10000,
        "typical_amount_max": 750000,
        "routing_email": "ap@coastaldevelopment.com",
        "review_contact": "finance@coastaldevelopment.com",
    },
    {
        "id": "entity_16_re",
        "name": "Westside Commercial Realty",
        "canonical_name": "westside commercial realty",
        "vertical": "real_estate",
        "address_patterns": ["Westside Business Hub", "600 West Ave", "WCR"],
        "known_vendor_categories": [
            "Leasing Management", "Tenant Fit-Out", "Cleaning", "Security",
            "IT Infrastructure", "Utilities Management", "Signage",
        ],
        "po_number_format": r"WCR-\d{4}-\d{4}",
        "typical_amount_min": 2000,
        "typical_amount_max": 200000,
        "routing_email": "ap@westsiderealty.com",
        "review_contact": "finance@westsiderealty.com",
    },
    {
        "id": "entity_17_re",
        "name": "Northgate Property Holdings",
        "canonical_name": "northgate property holdings",
        "vertical": "real_estate",
        "address_patterns": ["Northgate Tower", "101 North Blvd", "NPH"],
        "known_vendor_categories": [
            "Property Maintenance", "Landscaping", "HVAC", "Electrical",
            "Elevator", "Fire Safety", "Roofing",
        ],
        "po_number_format": r"NPH-\d{4}-\d{4}",
        "typical_amount_min": 1500,
        "typical_amount_max": 150000,
        "routing_email": "ap@northgateholdings.com",
        "review_contact": "finance@northgateholdings.com",
    },
    {
        "id": "entity_18_re",
        "name": "Eastview Retail Centers",
        "canonical_name": "eastview retail centers",
        "vertical": "real_estate",
        "address_patterns": ["Eastview Mall", "Eastview Retail Park", "ERC"],
        "known_vendor_categories": [
            "Retail Property Management", "Common Area Maintenance", "Security",
            "Cleaning", "Parking", "Signage", "Marketing",
        ],
        "po_number_format": r"ERC-\d{4}-\d{4}",
        "typical_amount_min": 2000,
        "typical_amount_max": 300000,
        "routing_email": "ap@eastviewretail.com",
        "review_contact": "finance@eastviewretail.com",
    },
    {
        "id": "entity_19_re",
        "name": "Downtown Mixed-Use Properties",
        "canonical_name": "downtown mixed use properties",
        "vertical": "real_estate",
        "address_patterns": ["Downtown Core", "500 City Centre", "DMP"],
        "known_vendor_categories": [
            "Property Maintenance", "Mixed-Use Cleaning", "Concierge",
            "Security", "Utility Management", "Tenant Services",
        ],
        "po_number_format": r"DMP-\d{4}-\d{4}",
        "typical_amount_min": 3000,
        "typical_amount_max": 250000,
        "routing_email": "ap@downtownmixeduse.com",
        "review_contact": "finance@downtownmixeduse.com",
    },
    {
        "id": "entity_20_re",
        "name": "Greenfield Residential Communities",
        "canonical_name": "greenfield residential communities",
        "vertical": "real_estate",
        "address_patterns": ["Greenfield Estates", "Greenfield Commons", "GRC"],
        "known_vendor_categories": [
            "Landscaping", "Community Management", "Maintenance",
            "Pool Services", "Playground Equipment", "Utilities",
        ],
        "po_number_format": r"GRC-\d{4}-\d{4}",
        "typical_amount_min": 1000,
        "typical_amount_max": 80000,
        "routing_email": "ap@greenfieldcommunities.com",
        "review_contact": "finance@greenfieldcommunities.com",
    },

    # ── Wellness (8) ──────────────────────────────────────────────────────────
    {
        "id": "entity_21_w",
        "name": "Serenity Wellness Studios",
        "canonical_name": "serenity wellness studios",
        "vertical": "wellness",
        "address_patterns": ["Wellness District", "77 Serenity Lane", "SWS"],
        "known_vendor_categories": [
            "Spa Supplies", "Essential Oils", "Fitness Equipment", "Towels & Linens",
            "Cleaning", "Supplements", "Candles", "Aromatherapy",
        ],
        "po_number_format": r"SWS-\d{4}-\d{4}",
        "typical_amount_min": 200,
        "typical_amount_max": 15000,
        "routing_email": "ap@serenitywellness.com",
        "review_contact": "finance@serenitywellness.com",
    },
    {
        "id": "entity_22_w",
        "name": "Pure Life E-Commerce",
        "canonical_name": "pure life ecommerce",
        "vertical": "wellness",
        "address_patterns": ["Pure Life Warehouse", "888 Commerce Way", "PLE"],
        "known_vendor_categories": [
            "Health Supplements", "Organic Products", "Packaging", "Shipping Supplies",
            "Digital Marketing", "Web Services", "Photography",
        ],
        "po_number_format": r"PLE-\d{4}-\d{4}",
        "typical_amount_min": 1000,
        "typical_amount_max": 80000,
        "routing_email": "ap@purelife.com",
        "review_contact": "finance@purelife.com",
    },
    {
        "id": "entity_23_w",
        "name": "Vitality Health Retail",
        "canonical_name": "vitality health retail",
        "vertical": "wellness",
        "address_patterns": ["Vitality Plaza", "444 Health Blvd", "VHR"],
        "known_vendor_categories": [
            "Health Products", "Supplements", "Retail Fixtures", "Packaging",
            "IT Services", "POS Systems", "Display Materials",
        ],
        "po_number_format": r"VHR-\d{4}-\d{4}",
        "typical_amount_min": 500,
        "typical_amount_max": 50000,
        "routing_email": "ap@vitalityhealth.com",
        "review_contact": "finance@vitalityhealth.com",
    },
    {
        "id": "entity_24_w",
        "name": "Elite Fitness Chain",
        "canonical_name": "elite fitness chain",
        "vertical": "wellness",
        "address_patterns": ["Elite Fitness HQ", "222 Active Way", "EFC"],
        "known_vendor_categories": [
            "Gym Equipment", "Personal Training Supplies", "Supplements",
            "Sports Apparel", "Cleaning", "Technology", "Music Licensing",
        ],
        "po_number_format": r"EFC-\d{4}-\d{4}",
        "typical_amount_min": 500,
        "typical_amount_max": 40000,
        "routing_email": "ap@elitefitness.com",
        "review_contact": "finance@elitefitness.com",
    },
    {
        "id": "entity_25_w",
        "name": "Botanical Spa & Wellness",
        "canonical_name": "botanical spa wellness",
        "vertical": "wellness",
        "address_patterns": ["Botanical Gardens District", "18 Blossom Rd", "BSW"],
        "known_vendor_categories": [
            "Botanical Skincare", "Organic Oils", "Spa Equipment", "Linen",
            "Aromatherapy", "Herbal Products", "Cleaning",
        ],
        "po_number_format": r"BSW-\d{4}-\d{4}",
        "typical_amount_min": 300,
        "typical_amount_max": 20000,
        "routing_email": "ap@botanicalspa.com",
        "review_contact": "finance@botanicalspa.com",
    },
    {
        "id": "entity_26_w",
        "name": "Mind & Body Clinic Network",
        "canonical_name": "mind body clinic network",
        "vertical": "wellness",
        "address_patterns": ["Clinic District", "400 Wellness Ave", "MBC"],
        "known_vendor_categories": [
            "Medical Supplies", "Therapy Equipment", "Supplements",
            "Mental Health Resources", "Cleaning", "Reception Supplies",
        ],
        "po_number_format": r"MBC-\d{4}-\d{4}",
        "typical_amount_min": 500,
        "typical_amount_max": 30000,
        "routing_email": "ap@mindbodyclinic.com",
        "review_contact": "finance@mindbodyclinic.com",
    },
    {
        "id": "entity_27_w",
        "name": "Active Life Sports Centers",
        "canonical_name": "active life sports centers",
        "vertical": "wellness",
        "address_patterns": ["Active Life Complex", "90 Sports Park Dr", "ALS"],
        "known_vendor_categories": [
            "Sports Equipment", "Court Maintenance", "Pool Chemicals",
            "Uniforms", "Catering", "IT Systems", "Cleaning",
        ],
        "po_number_format": r"ALS-\d{4}-\d{4}",
        "typical_amount_min": 500,
        "typical_amount_max": 55000,
        "routing_email": "ap@activelifesports.com",
        "review_contact": "finance@activelifesports.com",
    },
    {
        "id": "entity_28_w",
        "name": "NutriLife Health Stores",
        "canonical_name": "nutrilife health stores",
        "vertical": "wellness",
        "address_patterns": ["NutriLife Distribution", "777 Nutrition Blvd", "NLH"],
        "known_vendor_categories": [
            "Nutritional Products", "Vitamins & Minerals", "Organic Food",
            "Packaging", "Retail Displays", "Refrigeration",
        ],
        "po_number_format": r"NLH-\d{4}-\d{4}",
        "typical_amount_min": 1000,
        "typical_amount_max": 60000,
        "routing_email": "ap@nutrilifehealth.com",
        "review_contact": "finance@nutrilifehealth.com",
    },

    # ── Food & Beverage (8) ───────────────────────────────────────────────────
    {
        "id": "entity_29_fb",
        "name": "The Harbour Restaurant Group",
        "canonical_name": "harbour restaurant group",
        "vertical": "food_beverage",
        "address_patterns": ["Harbour Waterfront", "Harbour Dining District", "HRG"],
        "known_vendor_categories": [
            "Food & Produce", "Seafood", "Beverage", "Kitchen Equipment",
            "Cleaning", "Linen", "Uniforms", "POS Systems",
        ],
        "po_number_format": r"HRG-\d{4}-\d{4}",
        "typical_amount_min": 500,
        "typical_amount_max": 35000,
        "routing_email": "ap@harbourrestaurants.com",
        "review_contact": "finance@harbourrestaurants.com",
    },
    {
        "id": "entity_30_fb",
        "name": "Summit Catering & Events",
        "canonical_name": "summit catering events",
        "vertical": "food_beverage",
        "address_patterns": ["Summit Catering HQ", "Catering Industrial Estate", "SCE"],
        "known_vendor_categories": [
            "Food & Produce", "Catering Equipment", "Event Hire", "Linen",
            "Beverages", "Staffing", "Transport",
        ],
        "po_number_format": r"SCE-\d{4}-\d{4}",
        "typical_amount_min": 1000,
        "typical_amount_max": 80000,
        "routing_email": "ap@summitcatering.com",
        "review_contact": "finance@summitcatering.com",
    },
    {
        "id": "entity_31_fb",
        "name": "Pacific Farm-to-Table Restaurants",
        "canonical_name": "pacific farm to table",
        "vertical": "food_beverage",
        "address_patterns": ["Farm-to-Table District", "Organic Food Quarter", "PFT"],
        "known_vendor_categories": [
            "Organic Produce", "Local Farms", "Artisan Suppliers", "Beverages",
            "Kitchen Supplies", "Cleaning", "Packaging",
        ],
        "po_number_format": r"PFT-\d{4}-\d{4}",
        "typical_amount_min": 300,
        "typical_amount_max": 25000,
        "routing_email": "ap@pacificfarmtotable.com",
        "review_contact": "finance@pacificfarmtotable.com",
    },
    {
        "id": "entity_32_fb",
        "name": "Coastal Brew & Bistro",
        "canonical_name": "coastal brew bistro",
        "vertical": "food_beverage",
        "address_patterns": ["Coastal Brewing District", "Craft Beer Quarter", "CBB"],
        "known_vendor_categories": [
            "Brewing Supplies", "Hops & Malt", "Food Supplies", "Bar Equipment",
            "Cleaning", "Refrigeration", "Tap Systems",
        ],
        "po_number_format": r"CBB-\d{4}-\d{4}",
        "typical_amount_min": 500,
        "typical_amount_max": 30000,
        "routing_email": "ap@coastalbrew.com",
        "review_contact": "finance@coastalbrew.com",
    },
    {
        "id": "entity_33_fb",
        "name": "Artisan Bakery Chain",
        "canonical_name": "artisan bakery chain",
        "vertical": "food_beverage",
        "address_patterns": ["Artisan Quarter", "Bakery Industrial Park", "ABC"],
        "known_vendor_categories": [
            "Flour & Grains", "Dairy", "Packaging", "Bakery Equipment",
            "Cleaning Supplies", "Retail Displays", "Refrigeration",
        ],
        "po_number_format": r"ABC-\d{4}-\d{4}",
        "typical_amount_min": 200,
        "typical_amount_max": 20000,
        "routing_email": "ap@artisanbakery.com",
        "review_contact": "finance@artisanbakery.com",
    },
    {
        "id": "entity_34_fb",
        "name": "The Urban Kitchen Group",
        "canonical_name": "urban kitchen group",
        "vertical": "food_beverage",
        "address_patterns": ["Urban Dining Precinct", "Kitchen Quarter", "UKG"],
        "known_vendor_categories": [
            "Food & Produce", "Beverages", "Kitchen Equipment", "POS Systems",
            "Delivery Packaging", "Cleaning", "Marketing",
        ],
        "po_number_format": r"UKG-\d{4}-\d{4}",
        "typical_amount_min": 400,
        "typical_amount_max": 40000,
        "routing_email": "ap@urbankitchengroup.com",
        "review_contact": "finance@urbankitchengroup.com",
    },
    {
        "id": "entity_35_fb",
        "name": "Fine Dining Collections",
        "canonical_name": "fine dining collections",
        "vertical": "food_beverage",
        "address_patterns": ["Fine Dining Mile", "Premium Restaurant Row", "FDC"],
        "known_vendor_categories": [
            "Premium Produce", "Fine Wine & Spirits", "Luxury Tableware",
            "Linen", "Floral", "Kitchen Equipment", "Cleaning",
        ],
        "po_number_format": r"FDC-\d{4}-\d{4}",
        "typical_amount_min": 1000,
        "typical_amount_max": 90000,
        "routing_email": "ap@finediningcollections.com",
        "review_contact": "finance@finediningcollections.com",
    },
    {
        "id": "entity_36_fb",
        "name": "Waterfront Café Network",
        "canonical_name": "waterfront cafe network",
        "vertical": "food_beverage",
        "address_patterns": ["Waterfront Promenade", "Café Row", "WCN"],
        "known_vendor_categories": [
            "Coffee Beans", "Milk & Dairy", "Baked Goods", "Packaging",
            "Equipment Maintenance", "Cleaning", "Uniforms",
        ],
        "po_number_format": r"WCN-\d{4}-\d{4}",
        "typical_amount_min": 200,
        "typical_amount_max": 18000,
        "routing_email": "ap@waterfrontcafe.com",
        "review_contact": "finance@waterfrontcafe.com",
    },

    # ── Retail (7) ────────────────────────────────────────────────────────────
    {
        "id": "entity_37_rt",
        "name": "Coastal Lifestyle Retail",
        "canonical_name": "coastal lifestyle retail",
        "vertical": "retail",
        "address_patterns": ["Coastal Shopping Centre", "Lifestyle Quarter", "CLR"],
        "known_vendor_categories": [
            "Apparel", "Homeware", "Accessories", "Retail Fixtures",
            "IT & POS", "Cleaning", "Packaging",
        ],
        "po_number_format": r"CLR-\d{4}-\d{4}",
        "typical_amount_min": 500,
        "typical_amount_max": 60000,
        "routing_email": "ap@coastallifestyle.com",
        "review_contact": "finance@coastallifestyle.com",
    },
    {
        "id": "entity_38_rt",
        "name": "Pacific Fashion Group",
        "canonical_name": "pacific fashion group",
        "vertical": "retail",
        "address_patterns": ["Fashion District", "Pacific Fashion HQ", "PFG"],
        "known_vendor_categories": [
            "Clothing Manufacturers", "Fabric Suppliers", "Accessories",
            "Photography", "Marketing", "Display Materials", "Shipping",
        ],
        "po_number_format": r"PFG-\d{4}-\d{4}",
        "typical_amount_min": 2000,
        "typical_amount_max": 150000,
        "routing_email": "ap@pacificfashion.com",
        "review_contact": "finance@pacificfashion.com",
    },
    {
        "id": "entity_39_rt",
        "name": "Homestyle Furnishings",
        "canonical_name": "homestyle furnishings",
        "vertical": "retail",
        "address_patterns": ["Furniture Quarter", "Homestyle Showroom", "HSF"],
        "known_vendor_categories": [
            "Furniture Manufacturers", "Fabric & Upholstery", "Lighting",
            "Accessories", "Delivery Services", "Display Fixtures",
        ],
        "po_number_format": r"HSF-\d{4}-\d{4}",
        "typical_amount_min": 1000,
        "typical_amount_max": 200000,
        "routing_email": "ap@homestylefurnishings.com",
        "review_contact": "finance@homestylefurnishings.com",
    },
    {
        "id": "entity_40_rt",
        "name": "Outdoor & Adventure Gear",
        "canonical_name": "outdoor adventure gear",
        "vertical": "retail",
        "address_patterns": ["Adventure Park District", "Outdoor Retail Zone", "OAG"],
        "known_vendor_categories": [
            "Outdoor Equipment", "Apparel", "Camping Gear", "Water Sports",
            "Climbing Equipment", "Footwear", "Navigation Tech",
        ],
        "po_number_format": r"OAG-\d{4}-\d{4}",
        "typical_amount_min": 1000,
        "typical_amount_max": 100000,
        "routing_email": "ap@outdooradventuregear.com",
        "review_contact": "finance@outdooradventuregear.com",
    },
    {
        "id": "entity_41_rt",
        "name": "Luxury Goods Boutiques",
        "canonical_name": "luxury goods boutiques",
        "vertical": "retail",
        "address_patterns": ["Luxury Mile", "Premium Retail District", "LGB"],
        "known_vendor_categories": [
            "Luxury Brands", "Jewellery Suppliers", "Premium Packaging",
            "Security", "Cleaning", "Display Cases", "Insurance",
        ],
        "po_number_format": r"LGB-\d{4}-\d{4}",
        "typical_amount_min": 5000,
        "typical_amount_max": 500000,
        "routing_email": "ap@luxuryboutiques.com",
        "review_contact": "finance@luxuryboutiques.com",
    },
    {
        "id": "entity_42_rt",
        "name": "Tech & Electronics Stores",
        "canonical_name": "tech electronics stores",
        "vertical": "retail",
        "address_patterns": ["Tech District", "Electronics Quarter", "TES"],
        "known_vendor_categories": [
            "Consumer Electronics", "Accessories", "Display Technology",
            "Packaging", "Repair Parts", "IT Infrastructure", "Security",
        ],
        "po_number_format": r"TES-\d{4}-\d{4}",
        "typical_amount_min": 2000,
        "typical_amount_max": 300000,
        "routing_email": "ap@techelectronics.com",
        "review_contact": "finance@techelectronics.com",
    },
    {
        "id": "entity_43_rt",
        "name": "Children's World Retail",
        "canonical_name": "childrens world retail",
        "vertical": "retail",
        "address_patterns": ["Family Shopping Centre", "Kids Quarter", "CWR"],
        "known_vendor_categories": [
            "Toys", "Children's Apparel", "Baby Products", "Educational Supplies",
            "Safety Equipment", "Display Fixtures", "Packaging",
        ],
        "po_number_format": r"CWR-\d{4}-\d{4}",
        "typical_amount_min": 500,
        "typical_amount_max": 70000,
        "routing_email": "ap@childrensworld.com",
        "review_contact": "finance@childrensworld.com",
    },

    # ── Construction & Development (5) ────────────────────────────────────────
    {
        "id": "entity_44_cd",
        "name": "Pacific Construction Group",
        "canonical_name": "pacific construction group",
        "vertical": "construction",
        "address_patterns": ["Construction Hub", "Pacific Building Yard", "PCG"],
        "known_vendor_categories": [
            "Building Materials", "Concrete", "Steel", "Electrical",
            "Plumbing", "Equipment Hire", "Safety Supplies",
        ],
        "po_number_format": r"PCG-\d{4}-\d{4}",
        "typical_amount_min": 5000,
        "typical_amount_max": 2000000,
        "routing_email": "ap@pacificconstruction.com",
        "review_contact": "finance@pacificconstruction.com",
    },
    {
        "id": "entity_45_cd",
        "name": "Summit Interior Fit-Outs",
        "canonical_name": "summit interior fitouts",
        "vertical": "construction",
        "address_patterns": ["Interior Design Hub", "Fit-Out District", "SIF"],
        "known_vendor_categories": [
            "Flooring", "Carpentry", "Joinery", "Paint & Finishes",
            "Lighting", "Furniture", "AV Systems",
        ],
        "po_number_format": r"SIF-\d{4}-\d{4}",
        "typical_amount_min": 3000,
        "typical_amount_max": 500000,
        "routing_email": "ap@summitfitouts.com",
        "review_contact": "finance@summitfitouts.com",
    },
    {
        "id": "entity_46_cd",
        "name": "Coastal Infrastructure Works",
        "canonical_name": "coastal infrastructure works",
        "vertical": "construction",
        "address_patterns": ["Infrastructure Yard", "Civil Works Depot", "CIW"],
        "known_vendor_categories": [
            "Civil Engineering", "Road Works", "Drainage", "Utilities",
            "Marine Construction", "Equipment", "Safety",
        ],
        "po_number_format": r"CIW-\d{4}-\d{4}",
        "typical_amount_min": 20000,
        "typical_amount_max": 5000000,
        "routing_email": "ap@coastalinfrastructure.com",
        "review_contact": "finance@coastalinfrastructure.com",
    },
    {
        "id": "entity_47_cd",
        "name": "Urban Renovation Projects",
        "canonical_name": "urban renovation projects",
        "vertical": "construction",
        "address_patterns": ["Renovation Hub", "Urban Renewal District", "URP"],
        "known_vendor_categories": [
            "Demolition", "Structural Repairs", "Plumbing", "Electrical",
            "Plastering", "Tiling", "Heritage Restoration",
        ],
        "po_number_format": r"URP-\d{4}-\d{4}",
        "typical_amount_min": 2000,
        "typical_amount_max": 300000,
        "routing_email": "ap@urbanrenovation.com",
        "review_contact": "finance@urbanrenovation.com",
    },
    {
        "id": "entity_48_cd",
        "name": "Greenland Landscaping Division",
        "canonical_name": "greenland landscaping division",
        "vertical": "construction",
        "address_patterns": ["Landscaping Depot", "Garden Works Centre", "GLD"],
        "known_vendor_categories": [
            "Plants & Trees", "Irrigation Systems", "Outdoor Furniture",
            "Turf", "Fencing", "Hardscaping", "Equipment",
        ],
        "po_number_format": r"GLD-\d{4}-\d{4}",
        "typical_amount_min": 1000,
        "typical_amount_max": 200000,
        "routing_email": "ap@greenlandscaping.com",
        "review_contact": "finance@greenlandscaping.com",
    },

    # ── Technology & Services (5) ─────────────────────────────────────────────
    {
        "id": "entity_49_ts",
        "name": "Inspiration Tech Corp HQ",
        "canonical_name": "inspiration tech corp",
        "vertical": "technology",
        "address_patterns": ["ITC Tower", "Tech Innovation District", "ITC"],
        "known_vendor_categories": [
            "Software Licences", "Cloud Services", "Hardware", "IT Support",
            "Cybersecurity", "Consulting", "Office Supplies",
        ],
        "po_number_format": r"ITC-\d{4}-\d{4}",
        "typical_amount_min": 500,
        "typical_amount_max": 200000,
        "routing_email": "ap@inspirationtechcorp.com",
        "review_contact": "finance@inspirationtechcorp.com",
    },
    {
        "id": "entity_50_ts",
        "name": "Digital Growth Marketing",
        "canonical_name": "digital growth marketing",
        "vertical": "technology",
        "address_patterns": ["Digital Hub", "Marketing Quarter", "DGM"],
        "known_vendor_categories": [
            "Paid Advertising", "Content Creation", "SEO Services",
            "Design Agency", "Print Media", "PR Services", "Analytics",
        ],
        "po_number_format": r"DGM-\d{4}-\d{4}",
        "typical_amount_min": 1000,
        "typical_amount_max": 80000,
        "routing_email": "ap@digitalgrowth.com",
        "review_contact": "finance@digitalgrowth.com",
    },
]
